openapi: 3.0.0
info:
  description: This API allows sending and receiving payment through the DinoPay platform.
  title: DinoPay API
  version: 1.0.0
servers:
- url: /
tags:
- description: Payments API
  externalDocs: {}
  name: payments
paths:
  /payments:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/payment'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/payment'
          description: Created
        "400":
          content:
            text/html:
              schema:
                $ref: '#/components/schemas/errorMessage'
          description: The provided parameters are incorrect
      summary: Create a new payment
      tags:
      - payments
  /webhooks/subscriptions:
    post:
      callbacks:
        eventOccurred:
          callbackUrl:
            post:
              operationId: eventOccurred_callbackUrlPost
              requestBody:
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/event'
                description: Notifies that a new event occured
              responses:
                "200":
                  description: Return a 200 status to indicate that the data was received
                    successfully
              x-callback-request: true
      requestBody:
        $ref: '#/components/requestBodies/inline_object'
        content:
          application/json:
            schema:
              properties:
                callbackUrl:
                  example: https://myserver.com/send/callback/here
                  format: uri
                  type: string
                eventType:
                  type: string
              required:
              - callbackUrl
              - eventType
              type: object
        required: true
      responses:
        "201":
          description: Webhook created
      summary: Subscribe to events
      tags:
      - payments
components:
  requestBodies:
    inline_object:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_object'
      required: true
  schemas:
    errorMessage:
      description: A text message describing an error
      maxLength: 256
      type: string
    payment:
      description: A transfer of money from a source account to a destination account
      example:
        createdAt: 6
        amount: 0.8008281904610115
        sourceAccount:
          accountHolder: accountHolder
          accountNumber: accountNumber
        currency: currency
        id: id
        customerTransactionId: customerTransactionId
        destinationAccount:
          accountHolder: accountHolder
          accountNumber: accountNumber
        updatedAt: 1
      properties:
        id:
          description: Payment UUID
          type: string
        amount:
          description: Payment amount
          type: number
        currency:
          description: Payment currency
          type: string
        sourceAccount:
          $ref: '#/components/schemas/account'
        destinationAccount:
          $ref: '#/components/schemas/account'
        status:
          $ref: '#/components/schemas/paymentStatus'
        customerTransactionId:
          description: A unique id generated by the customer for this payment
          type: string
        createdAt:
          description: Date and time when the payment was created expressed as a Unix
            timestamp
          type: integer
        updatedAt:
          description: Date and time when of the last update made to the payment expressed
            as a Unix timestamp
          type: integer
      required:
      - amount
      - destinationAccount
      - sourceAccount
      type: object
    account:
      description: A DinoPay account
      example:
        accountHolder: accountHolder
        accountNumber: accountNumber
      properties:
        accountHolder:
          description: Name of the account owner of the account
          type: string
        accountNumber:
          description: Number that identifies the account
          type: string
      required:
      - accountHolder
      - accountNumber
      type: object
    paymentStatus:
      description: Status of the payment
      enum:
      - pending
      - confirmed
      - rejected
      type: string
    event:
      description: A payment was updated
      properties:
        id:
          description: Event UUID
          type: string
        type:
          description: The event type
          type: string
        time:
          description: Timestamp of when the occurrence happened
          type: string
        data:
          description: Event payload
          oneOf:
          - $ref: '#/components/schemas/paymentUpdated'
          - $ref: '#/components/schemas/paymentCreated'
          type: object
      required:
      - data
      - id
      - time
      - type
      type: object
    paymentCreated:
      description: A new payment was created
      properties:
        payment:
          $ref: '#/components/schemas/payment'
      required:
      - payment
      type: object
    paymentUpdated:
      description: A payment was updated
      properties:
        payment:
          $ref: '#/components/schemas/payment'
      required:
      - payment
      type: object
    inline_object:
      properties:
        callbackUrl:
          example: https://myserver.com/send/callback/here
          format: uri
          type: string
        eventType:
          type: string
      required:
      - callbackUrl
      - eventType
      type: object
