/*
 * DinoPay API
 *
 * This API allows sending and receiving payment through the DinoPay platform.
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// PaymentCreated A new payment was created
type PaymentCreated struct {
	Payment Payment `json:"payment"`
}

// NewPaymentCreated instantiates a new PaymentCreated object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentCreated(payment Payment, ) *PaymentCreated {
	this := PaymentCreated{}
	this.Payment = payment
	return &this
}

// NewPaymentCreatedWithDefaults instantiates a new PaymentCreated object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentCreatedWithDefaults() *PaymentCreated {
	this := PaymentCreated{}
	return &this
}

// GetPayment returns the Payment field value
func (o *PaymentCreated) GetPayment() Payment {
	if o == nil  {
		var ret Payment
		return ret
	}

	return o.Payment
}

// GetPaymentOk returns a tuple with the Payment field value
// and a boolean to check if the value has been set.
func (o *PaymentCreated) GetPaymentOk() (*Payment, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Payment, true
}

// SetPayment sets field value
func (o *PaymentCreated) SetPayment(v Payment) {
	o.Payment = v
}

func (o PaymentCreated) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["payment"] = o.Payment
	}
	return json.Marshal(toSerialize)
}

type NullablePaymentCreated struct {
	value *PaymentCreated
	isSet bool
}

func (v NullablePaymentCreated) Get() *PaymentCreated {
	return v.value
}

func (v *NullablePaymentCreated) Set(val *PaymentCreated) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentCreated) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentCreated) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentCreated(val *PaymentCreated) *NullablePaymentCreated {
	return &NullablePaymentCreated{value: val, isSet: true}
}

func (v NullablePaymentCreated) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentCreated) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


